"Pathogen (vim package manager)
execute pathogen#infect()
syntax on
filetype plugin indent on

"Use jk as <esc> alternative
inoremap jk <Esc>

"Use number lines
set number

"Solarized color scheme
set background=dark
colorscheme solarized

" Execute file being edited with <Shift> + e:
map <buffer> <S-e> :w<CR>:!/usr/bin/env python % <CR>

" Set a backup directory
set backup
set backupdir=~/tmp

" No backup files
"set nobackup

" No swap files
set noswapfile
